name: Publish new beta release from development
on:
  pull_request:
    types: [closed]
    branches:
      - development

jobs:
  install:
    # This ensures that this workflow only runs when a PR is being merged to 'development'
    if: github.event.pull_request.merged == true
    name: Install and cache dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          # Removes credentials
          persist-credentials: false
          fetch-depth: 0

      # Restore the previous NPM modules and Cypress binary archives.
      # Any updated archives will be saved automatically after the entire
      # workflow successfully finishes.
      # See https://github.com/actions/cache
      # we use exact restore key to avoid NPM module snowballing
      # https://glebbahmutov.com/blog/do-not-let-npm-cache-snowball/
      - name: Cache central NPM modules
        uses: actions/cache@v2.1.6
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Cache local node_modules to pass to testing jobs
      - name: Cache local node_modules
        uses: actions/cache@v2.1.4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

  update-version-changelog:
    # This ensures that this workflow only runs when a PR is being merged to 'development'
    if: github.event.pull_request.merged == true
    name: Update version and CHANGELOG
    runs-on: ubuntu-latest
    needs: install
    env:
      VERSION: ''
    steps:
      - name: Checkout development
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Cache local node_modules
        uses: actions/cache@v2.1.4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Setup .npmrc file to publish to npm
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      # This is required for publishing from GH Actions
      - name: Set GitHub Action user
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      # Build the component library
      - name: Build new package
        run: yarn run build

      # Update the version in package.json for the beta release
      - name: Tag beta release
        run: yarn release-beta

  push-to-development:
    # This ensures that this workflow only runs when a PR is being merged to 'development'
    if: github.event.pull_request.merged == true
    name: Push changes to development
    runs-on: ubuntu-latest
    needs: [install, update-version-changelog]
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          # Removes credentials
          persist-credentials: false
          fetch-depth: 0

      # Ensure development is in sync
      - name: Push to development
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_ACTION_PAT }}
          branch: development

  deploy-to-gh-pages:
    # This ensures that this workflow only runs when a PR is being merged to 'development'
    if: github.event.pull_request.merged == true
    name: Deploy to GH Pages
    runs-on: ubuntu-latest
    needs: [install, update-version-changelog, push-to-development]
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          # Removes credentials
          persist-credentials: false
          fetch-depth: 0

      - name: Cache local node_modules
        uses: actions/cache@v2.1.4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Build Storybook
        run: yarn storybook-build

      - name: Deploy Storybook to GH Pages
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GH_ACTION_PAT }}
          BRANCH: gh-pages
          FOLDER: storybook-dist
          CLEAN: true

  publish-beta-to-npm:
    # This ensures that this workflow only runs when a PR is being merged to 'development'
    if: github.event.pull_request.merged == true
    name: Deploy beta to npm
    runs-on: ubuntu-latest
    needs: [install, update-version-changelog, push-to-development]
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          # Removes credentials
          persist-credentials: false
          fetch-depth: 0

      - name: Cache local node_modules
        uses: actions/cache@v2.1.4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Setup .npmrc file to publish to npm
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      # This is required for publishing from GH Actions
      - name: Set GitHub Action user
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      # Build the component library
      - name: Build new package
        run: yarn run build

      # Publish a new beta release to NPM
      - name: Publish @f-design/component-library beta release from development
        run: npm publish --tag beta --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

  post-slack-notification:
    # This ensures that this workflow only runs when a PR is being merged to 'development'
    if: github.event.pull_request.merged == true
    name: Notify Slack of new beta release
    runs-on: ubuntu-latest
    needs:
      [
        install,
        update-version-changelog,
        push-to-development,
        deploy-to-gh-pages,
        publish-beta-to-npm,
      ]
    env:
      VERSION: ''
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          # Removes credentials
          persist-credentials: false
          fetch-depth: 0

      # Extract the canary version number to post in a comment
      - name: Capture new version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      # Post Slack notification about beta release
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: component-library
          SLACK_ICON_EMOJI: ':sewing_needle:'
          SLACK_MESSAGE: |
            Version: ${{ env.VERSION }}
            Install with `yarn add @f-design/component-library@beta`
          SLACK_TITLE: Beta release of Component Library successful!
          SLACK_USERNAME: FWD-Bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
