name: Publish new release from main
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build-release:
    # This ensures that this workflow only runs when a PR is being merged to 'main'
    if: github.event.pull_request.merged == true
    name: Publish new release from main
    runs-on: ubuntu-latest
    env:
      VERSION: ''
    steps:
      - name: Checkout development
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0

      # Restore the previous NPM modules and Cypress binary archives.
      # Any updated archives will be saved automatically after the entire
      # workflow successfully finishes.
      # See https://github.com/actions/cache
      # we use exact restore key to avoid NPM module snowballing
      # https://glebbahmutov.com/blog/do-not-let-npm-cache-snowball/
      - name: Cache central NPM modules
        uses: actions/cache@v2.1.6
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Cache local node_modules to pass to testing jobs
      - name: Cache local node_modules
        uses: actions/cache@v2.1.4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Setup .npmrc file to publish to npm
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      # This is required for publishing from GH Actions
      - name: Set GitHub Action user
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      # Build the component library
      - name: Build new package
        run: yarn run build

      - name: Update CHANGELOG/version
        run: yarn release

      # Publish a new release to NPM
      - name: Publish @f-design/component-library from main
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      # Ensure main is in sync
      - name: Push to main
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_ACTION_PAT }}
          branch: main

      # Post Slack notification about release
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: component-library
          SLACK_ICON_EMOJI: ':sewing_needle:'
          SLACK_MESSAGE: |
            Version: ${{ env.VERSION }}
            Install with `yarn add @f-design/component-library`
          SLACK_TITLE: Release of Component Library successful!
          SLACK_USERNAME: FWD-Bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
